// flow-typed signature: 1db1114c345d6699f1ef4dc14f722a38
// flow-typed version: <<STUB>>/express-slash_v^2.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-slash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-slash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-slash/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-slash/index' {
  declare module.exports: $Exports<'express-slash'>;
}
declare module 'express-slash/index.js' {
  declare module.exports: $Exports<'express-slash'>;
}
declare module 'express-slash/test/index.js' {
  declare module.exports: $Exports<'express-slash/test/index'>;
}
